const preguntasRazonamientoNumerico = `Selecciona la respuesta correcta al planteamiento: En una jornada de 8 horas se pintan 10 metros cuadrados de pared y se emplean 6 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 25 metros cuadrados? ;20 horas y 15 litros de pintura;25 horas y 14 litros de pintura ;24 horas y 10 litros de pintura ;31 horas y 8 litros de pintura;1
Encuentra la respuesta correcta: El 80% de 20 semanas equivale a _____ días ;5;56;112;16;3
Encuentre el porcentaje correcto: Diariamente, el 35% del Ecovía va ocupado por hombres menores de 65 y el 35% por mujeres menores de 65. Del restante, 30% son mujeres, ¿qué porcentaje del total representan? ;30%;9%;21%;11%;2
Calcular el valor correcto para el planteamiento: Un patio de autos tiene 140 unidades, el 25% de ellos son rojos y el 25% negros. ¿Cuántos autos de cada color hay? ;25 rojos y 25 negros;25 rojos y 35 negros ;35 rojos y 25 negros;35 rojos y 35 negros;4
"Encuentra la respuesta correcta al planteamiento: En una competencia corre 26 km, camina 7 km; nada 2000 metros más, conduce en bicicleta otros 5000 metros. ¿De cuántos kilómetros fue su recorrido? ";40;41;38;39;1
Encuentra la respuesta correcta al planteamiento: Se vendió una camisa con una ganancia del 15% sobre el precio de costo. Si se ha vendido en $46, hallar el precio de costo. ;40;30;41;39;1
Encuentra la respuesta correcta al planteamiento: Varias familias van de paseo en 12 autos. Nueve autos llevan familias de 4 personas cada uno. En cuatro autos viajan tres personas y cuatro van ocupados por solo dos personas.  ¿Cuántas personas viajan en total? ;55;53;58;56;4
Calcular el valor correcto para el planteamiento: El ingreso promedio mensual de tres hermanos es de $1700. El mayor tiene un sueldo de $2000, el segundo gana $1700. ¿Cuál será el sueldo del hermano menor? ;1700;1550;1400;1500;3
Selecciona la respuesta correcta al planteamiento: El precio de un par de lámparas es de $1600 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 17%?;800;1072;936;926;3
Encuentre la respuesta correcta: Al adquirir un auto, cuyo precio es de $13000, nos hacen un descuento del 13%, ¿cuánto hay que pagar por el vehículo? ;9200;9099;11310;9100;3
Selecciona la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 60 km/h y se detiene 6 minutos cada hora. Si circula durante 9 horas, ¿cuántos kilómetros recorre en ese tiempo? ;450;508;486;540;3
Calcular el valor correcto para el planteamiento: El 19% de los anuncios en una ciudad son luminosos. Si en la ciudad hay 8500 anuncios, ¿cuántos anuncios no luminosos hay en toda la ciudad? ;81;1605;6885;1615;3
"Calcular el valor correcto para el planteamiento: En el colegio ""Rockero"", a 25 de sus 50 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 90 estudiantes y a 30 les gusta la cumbia. En el colegio ""Cumbiero"" hay 100 estudiantes y a 30 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia? ";"""Cumbiero"" y ""Rockero"" ";"""Salsero""";"""Cumbiero"" ";"""Rockero""";4
Encuentre la respuesta correcta: Si el dólar se devaluará cada año 4%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;89%;88%;84%;92%;1
Calcule la respuesta correcta : Si una pantalla cuesta $400, un monitor $60 y una USB $410, ¿cuánto debe pagarse por 2 pantallas, 5 monitores y 2 USB? ;870;1920;2020;2940;2
Encuentre la respuesta correcta: Si Semilla=$3, Fruto=$24, Árbol=$192, ¿cuántas frutos se pueden comprar por cada árbol? ;3;8;23;24;2
Calcular el valor correcto para el planteamiento: La nota final de Juan en Matemáticas es de 7.3 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 7.1 y en el segundo 7.2, ¿cuál fue su nota en el tercer examen?;7.5;7.6;7.9;7.3;2
Calcular el valor correcto para el planteamiento: Si Pedro tiene 14 años y su madre cuatro veces la edad que él. Cuando Pedro tenga 21 años, ¿cuántos tendrá su madre? ;62;63;56;64;2
Encuentra el porcentaje correcto: Una armadura está compuesta de 5 elementos: 16% de Zinc, 13% de Hierro, 15% de Carbono y 13% de Estaño, ¿cuál será el porcentaje de Bronce que posee? ;47%;53%;57%;43%;4
Selecciona la respuesta correcta al planteamiento: Tania y gloria desean comprar un departamento de $30000. Tania tiene el doble de ahorro que Gloria, pero para lograrlo, Tania debería tener el doble de dinero que tiene. ¿Cuánto dinero tiene Jorge? ;7500;6000;5000;10000;2
Encuentra la respuesta correcta: El 20% de 3 horas es equivalente en minutos a: ;144;37;20;36;4
Selecciona la respuesta correcta al planteamiento: Usted tiene 20 pelotas, regala 4, le roban 6, pierde 5 y compra otras 7. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 3 niños a los que debe entregar?;4;5;2;1;1
Encuentra la respuesta correcta: Los 3/5 de un número es 150, ¿cuánto será los 3/10 del mismo número? ;75;90;250;160;1
Encuentra la respuesta correcta: Los 3/5 de un número es 150, ¿cuánto será los 3/10 del mismo número? ;75;90;250;160;1
Selecciona la respuesta correcta al planteamiento: Un auto avanza 14 kilómetros, luego retrocede 800 metros, vuelve a avanzar 4 kilómetros, ¿cuántos metros avanzó realmente? ;1000;17200;16200;18200;2
Encuentra la respuesta correcta al planteamiento: En un hogar se utilizan 580 litros de agua, 360 litros se utilizan para bañarse, se lavan platos y ropa con 45 litros, se lavan los autos con el 5% y lo mismo se emplea en el jardín. ¿Cuántos litros se utilizan para el jardín? ";45;28;29;30;3
Calcular el valor correcto al planteamiento: El ingreso mensual de un especialista es de $1800. Al ascender a Coordinador, su sueldo aumentará 15%. ¿Cuál será su nuevo ingreso mensual? ;1270;2070;1150;1970;2
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 130 km/h y uno urbano lo hace a 70 km/h. Después de 9 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;470;610;540;575;3
Calcular el valor correcto al planteamiento: Los estudiantes aciertan en el 70% de las preguntas de una prueba nacional. Si la prueba tiene un total de 180 preguntas, en promedio, ¿en cuántas preguntas se espera que no acierten? ;125;30;54;59;3
Calcule la respue sta correcta : Si un viaje individual a Esmeraldas cuesta $150, uno a Manta $300 y uno a Galápagos $630, ¿cuánto costaría a una pareja hacer los 3 viajes en un año?;2060;2260;1080;2160;4
Encuentra la respuesta correcta al planteamiento: Para cenar, unos amigos piden 7 pizzas. Cada pizza tiene 8 rebanadas. Se comen el 71% en el restaurante, se llevan a casa el 17% y dejan lo demás. ¿Cuánto dejaron? ;11%;89%;88%;12%;4
Selecciona la respuesta correcta al planteamiento: Se desea distribuir 432 esferos, 459 cuadernos, 297 libros y 972 lápices entre 27 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?;15 esferos, 17 cuadernos, 11 libros y 36 lápices ;16 esferos, 17 cuadernos, 11 libros y 35 lápices;16 esferos, 17 cuadernos, 10 libros y 36 lápices ; 16 esferos, 17 cuadernos, 11 libros y 36 lápices ;4
Encuentra la respuesta correcta al planteamiento: Una familia compra 100 tacos. El 53% de ellos eran de carne, el 26% eran de pollo y los demás de queso, ¿cuántos eran de queso? ;78;30;79;21;4
Encuentra la respuesta correcta: Si 5 personas se comen 40 empanadas en 24 minutos, ¿cuánto demorarán 10 personas en comer la misma cantidad?  ;11;13;10;12;4
Encuentra la respuesta correcta al planteamiento: Una nave espacial, que puede viajar a 940 millas por hora, se mantiene en la base durante 11 horas desde las 04:00 am. Cuando despega, se desplaza a 850 millas por hora, ¿cuántas millas llevará recorridos a las 7:00 pm? ;3400;4250;127500;3750;1
Calcular el valor correcto al planteamiento: Una persona tiene $420 en cinco cupones y cuatro de ellos son de $95 cada uno, ¿de cuánto es el otro cupón? ;$50 ;$325; $40;$30;3
Encuentre el porcentaje correcto: Si una pareja gasta 31,5% de su salario en vivienda, 29,5% en comida, 13,5% en salud y 8,5% en educación, ¿de cuánto puede disponer para sus demás gastos? ;73%;17%;83%;16%;2
Encuntre el porcentaje correcto: El cuerpo humano está hecho de elementos químicos. Si 75% es Oxígeno, 17% Carbono, 12% Hidrógeno y 5% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;1%;9%;81%;97%;1
Encuentra la respuesta correcta al planteamiento: Si una motocicleta avanza a 120 km/h durante 20 minutos y luego a 80 km/h durante 30 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;80;120;100;105;1
Encuentra la respuesta correcta al planteamiento: Un avión hace 10 vuelos por mes. Cada mes, el piloto revisa 8 veces los controles, 7 los alerones, 12 el combustible. En cuatro meses, ¿cuántas veces habrá revisado los controles, los alerones y el combustible, respectivamente? ;32, 28, 48;30, 60, 120 ;28, 32, 48;48, 28, 32 ;1
Selecciona la respuesta correcta al planteamiento: Un auto avanza 16 kilómetros, luego retrocede 800 metros, vuelve a avanzar 3 kilómetros, ¿cuántos metros avanzó realmente? ;1200;17200;19200;18200;4
Encuentra la respuesta correcta al planteamiento: Los estudiantes aciertan en el 60% de las preguntas de una prueba nacional. Si la prueba tiene un total de 150 preguntas, en promedio, ¿en cuántas preguntas se espera que no acierten? ;40;60;90;65;2
Encuentra la respuesta correcta al planteamiento: Los 2/5 de un número es 80, ¿cuánto será los 3/10 del mismo número? ;60;168;200;32;1
Encuentre el porcentaje correcto: El cuerpo humano está hecho de elementos químicos. Si 65% es Oxígeno, 19% Carbono, 11% Hidrógeno y 3% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;3%;2%;95%;98%;2
Encuentra la respuesta correcta al planteamiento: Usted tiene 20 pelotas, regala 4, le roban 3, pierde 5 y compra otras 4. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 4 niños a los que debe entregar?;2;1;3;4;3
"Encuentra la respuesta correcta al planteamiento: En el colegio ""Rockero"", a 40 de sus 80 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 60 estudiantes y a 45 les gusta la cumbia. En el colegio ""Cumbiero"" hay 100 estudiantes y a 30 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia? ";"""Cumbiero"" y ""Rockero"" ";"""Salsero""";"""Cumbiero"" ";"""Rockero""";2
Encuentra la respuesta correcta al planteamiento: El ingreso promedio mensual de tres hermanos es de $1900. El mayor tiene un sueldo de $1500, el segundo gana $1200. ¿Cuál será el sueldo del hermano menor? ;3100;1900;3000;1350;3
Encuentra la respuesta correcta al planteamiento: Una nave espacial, que puede viajar a 900 millas por hora, se mantiene en la base durante 9 horas desde las 04:00 am. Cuando despega, se desplaza a 750 millas por hora, ¿cuántas millas llevará recorridos a las 9:00 pm? ;6000;7200;12750;6750;1
Selecciona la respuesta correcta al planteamiento: Si Pedro tiene 12 años y su madre cuatro veces la edad que él. Cuando Pedro tenga 23 años, ¿cuántos tendrá su madre? ;48;92;59;58;3
Encuentra la respuesta correcta al planteamiento: El precio de un par de lámparas es de $1200 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 12%?;744;662;600;672;4
Selecciona la respuesta correcta al planteamiento: Si una motocicleta avanza a 120 km/h durante 40 minutos y luego a 90 km/h durante 20 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;110;120;210;105;1
Encuentra la respuesta correcta al planteamiento: Un avión hace 10 vuelos por mes. Cada mes, el piloto revisa 9 veces los controles, 8 los alerones, 11 el combustible. En cinco meses, ¿cuántas veces habrá revisado los controles, los alerones y el combustible, respectivamente? ;45, 40, 55;90, 80, 110 ;45, 55, 40;55, 40, 45 ;1
Encuentra la respuesta correcta al planteamiento: Una familia compra 100 tacos. El 42% de ellos eran de carne, el 35% eran de pollo y los demás de queso, ¿cuántos eran de queso? ;77;76;23;32;3
Selecciona la respuesta correcta al planteamiento: La nota final de Juan en Matemáticas es de 9,5 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 9,2 y en el segundo 9,4, ¿cuál fue su nota en el tercer examen? ;9.9;10;9.7;9.6;1
Encuentra la respuesta correcta al planteamiento: Un patio de autos tiene 120 unidades, el 45% de ellos son rojos y el 5% negros. ¿Cuántos autos de cada color hay? ; 54 rojos y 5 negros;45 rojos y 6 negros ;54 rojos y 6 negros;45 rojos y 5 negros ;3
Encuentre el porcentaje correcto: Diariamente, el 55% del Ecovía va ocupado por hombres menores de 65 y el 25% por mujeres menores de 65. Del restante, 30% son mujeres, ¿qué porcentaje del total representan? ;30%;8%;6%;14%;3
encuentra la respuesta correcta al planteamiento: En una jornada de 8 horas se pintan 16 metros cuadrados de pared y se emplean 3 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 40 metros cuadrados? ;20 horas y 7,5 litros de pintura;24 horas y 8,5 litros de pintura ;80 horas y 8 litros de pintura ;40 horas y 6,5 litros de pintura ;1
Encuentre el porcentaje correcto: Si un profesional gasta 32,5% de su salario en vivienda, 26,5% en comida, 16,5% en salud y 8,5% en educación, ¿de cuánto puede disponer para sus demás gastos? ;16%;15%;84%;74%;1
Selecciona la respuesta correcta al planteamiento: Si una cama cuesta $300, un velador $60 y una silla $670, ¿cuánto debe pagarse por 3 camas, 6 veladores y 2 sillas? ;1030;3320;2700;2600;4
Encuentra la respuesta correcta al planteamiento: Luis tiene el doble de ahorro que Jorge, si entre ambos desean comprar un auto de $12.000, Luis debería tener el doble de dinero que tiene. ¿Cuánto dinero tiene Jorge? ;4000;2400;2000;3000;2
Encuentra la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 50 km/h y se detiene 6 minutos cada hora. Si circula durante 8 horas, ¿cuántos kilómetros recorre en ese tiempo? ;340;376;360;400;3
"Selecciona la respuesta correcta al planteamiento: En una competencia corre 18 km, camina 9 km; nada 2000 metros más, conduce en bicicleta otros 5000 metros. ¿De cuántos kilómetros fue su recorrido? ";35;34;33;32;2
Encuentra la respuesta correcta al planteamiento: El 18% de los anuncios en una ciudad son luminosos. Si en la ciudad hay 4500 anuncios, ¿cuántos anuncios no luminosos hay en toda la ciudad? ;82;800;3690;810;3
Encuentra la respuesta correcta al planteamiento: Se desea distribuir 338 esferos, 364 cuadernos, 260 libros y 962 lápices entre 26 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?;13 esferos, 14 cuadernos, 10 libros y 36 lápices ;12 esferos, 14 cuadernos, 10 libros y 37 lápices;13 esferos, 14 cuadernos, 10 libros y 37 lápices ;13 esferos, 14 cuadernos, 9 libros y 37 lápices ;3
"Selecciona la respuesta correcta al planteamiento: En un hogar se utilizan 340 litros de agua, 190 litros se utilizan para bañarse, se lavan platos y ropa con 34 litros, se lavan los autos con el 5% y lo mismo se emplea en el jardín. ¿Cuántos litros se utilizan para el jardín? ";18;34;16;17;4
Encuentra la respuesta correcta al planteamiento: Una persona camina durante 40 minutos a 9 km/h, luego pausa 3 minutos y corre otros 10 minutos a 6 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ;6;8;9;7;4
Encuentra la respuesta correcta al planteamiento: Una persona tiene $260 en cinco cupones y cuatro de ellos son de $45 cada uno, ¿de cuánto es el otro cupón? ;$70 ;$215;$80;$90;3
Encuentra la respuesta correcta al planteamiento: Si un viaje individual a Esmeraldas cuesta $400, uno a Manta $550 y uno a Galápagos $880, ¿cuánto costaría a una pareja hacer los 3 viajes en un año? ;3560;3760;3660;1830;3
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 180 km/h y uno urbano lo hace a 90 km/h. Después de 7 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;375;720;630;540;3
Encuentre el porcentaje correcto: Para cenar, unos amigos piden 7 pizzas. Cada pizza tiene 8 rebanadas. Se comen el 64% en el restaurante, se llevan a casa el 23% y dejan lo demás. ¿Cuánto dejaron? ;88%;13%;87%;12%;2
Encuentra la respuesta correcta al planteamiento: Se vendió una camisa con una ganancia del 15% sobre el precio de costo. Si se ha vendido en $92, hallar el precio de costo. ;79;80;81;78;2
Encuentra la respuesta correcta al planteamiento: El 20% de 9 horas es equivalente en minutos a:;20;108;109;432;2
Encuentra la respuesta correcta: Si 8 personas se comen 40 bocaditos en 15 minutos, ¿cuánto demorarán 10 personas en comer la misma cantidad? ;13;11;10;12;4
Selecciona la respuesta correcta al planteamiento: Varias familias van de paseo en 12 autos. Cinco autos llevan familias de 4 personas cada uno. En tres autos viajan tres personas y cuatro van ocupados por solo dos personas.  ¿Cuántas personas viajan en total? ;37;36;35;38;1
Encuentra la respuesta correcta al planteamiento: Si el dólar se devaluará cada año 8%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;84%;76%;68%;78%;4
Encuentra la respuesta correcta al planteamiento: Si Flor=$3, Rosa=$27, Planta=$81, ¿cuántas rosas se pueden comprar por cada planta? ;27;9;26;3;4
Encuentre el porcentaje correcto: Una espada está compuesta de 5 elementos: 14% de Zinc, 18% de Hierro, 13% de Carbono y 12% de Estaño, ¿cuál será el porcentaje de Bronce que posee? ;53%;47%;57%;43%;4
Selecciona la respuesta correcta al planteamiento: El ingreso mensual de un especialista es de $1200. Al ascender a Coordinador, su sueldo aumentará 35%. ¿Cuál será su nuevo ingreso mensual? ;1350;1520;1620;1420;3
Encuentra la respuesta correcta al planteamiento: El 20% de 70 semanas equivale a _____ días ;196;98;14;20;2
Encuentra la respuesta correcta al planteamiento: Al adquirir una lancha, cuyo precio es de $8000, nos hacen un descuento del 20%, ¿cuánto hay que pagar por el vehículo? ;6500;8020;6399;6400;4
Calcular el valor correcto al planteamiento: Una persona tiene $360 en cinco cupones y cuatro de ellos son de $35 cada uno, ¿de cuánto es el otro cupón? ; $250 ;$210;$220;$215;3
Selecciona la respuesta correcta al planteamiento: Usted tiene 40 raquetas, regala 8, le roban 6, pierde 10 y compra otras 8. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 6 niños a los que debe entregar?;3;2;4;1;3
"Selecciona la respuesta correcta al planteamient: En un día Luis corre 20 km, camina 12 km; nada 2500 metros más, conduce en bicicleta otros 7000 metros. ¿De cuántos kilómetros fue su recorrido? ";35;41.5;33;39.5;2
"Encuentra la respuesta correcta al planteamiento: En un hogar se utilizan 250 litros de agua, 120 litros se utilizan para bañarse, se lavan platos y ropa con 20 litros, se lavan los autos con el 8% y lo mismo se emplea en el jardín. ¿Cuántos litros se utilizan para el jardín? ";17;16;20;34;3
Encuentra la respuesta correcta al planteamiento: Una familia compra 100 quesadillas. El 25% de ellos eran de carne, el 60% eran de pollo y los demás de queso, ¿cuántos eran de queso? ;23;77;15;25;3
Encuentra la respuesta correcta al planteamiento: Para cenar, unos amigos piden 9 pizzas. Cada pizza tiene 12 rebanadas. Se comen el 75% en el restaurante, se llevan a casa el 15% y dejan lo demás. ¿Cuánto dejaron? ;13%;12%;10%;88%;3
Selecciona la respuesta correcta al planteamiento: Un auto avanza 32 kilómetros, luego retrocede 920 metros, vuelve a avanzar 8 kilómetros, ¿cuántos metros avanzó realmente? ;18200;12785;39080;40920;3
Encuentra la respuesta correcta al planteamiento: Una nave espacial, que puede viajar a 1200 millas por hora, se mantiene en la base durante 8 horas desde las 03:00 am. Cuando despega, se desplaza a 950 millas por hora, ¿cuántas millas llevará recorridos a las 7:00 pm? ;6000;6750;7600;12750;3
Encuentra la respuesta correcta al planteamiento: Un avión hace 15 vuelos por mes. Cada mes, el piloto revisa 8 veces los controles, 7 los alerones, 12 el combustible. En seis meses, ¿cuántas veces habrá revisado los controles, los alerones y el combustible, respectivamente? ;48, 42, 72;55, 40, 45 ;120, 105, 180;90, 80, 110;1
Calcular el valor correcto para el planteamiento: Si Carmen tiene 9 años y su madre cuatro veces la edad que ella. Cuando Carmen tenga 21 años, ¿cuántos tendrá su madre? ;39;35;34;48;4
Encuentra la respuesta correcta al planteamiento: Varias familias van de paseo en 8 autos. Tres autos llevan familias de 5 personas cada uno. En tres autos viajan cuatro personas y dos van ocupados por solo dos personas.  ¿Cuántas personas viajan en total? ;37;36;31;38;3
Encuentra el porcentaje correcto: Una puerta metálica está compuesta de 5 elementos: 16% de Zinc, 20% de Hierro, 9% de Carbono y 11% de Estaño, ¿cuál será el porcentaje de Bronce que posee? ;43%;57%;47%;44%;4
Encuentre el porcentaje correcto: Diariamente, el 60% del transporte urbano va ocupado por hombres menores de 65 y el 30% por mujeres menores de 65. Del restante, 25% son mujeres, ¿qué porcentaje del total representan? ;8%;1.4% ;2.5% ;3.0%;3
Encuntre el porcentaje correcto: Un compuesto químico está hecho de elementos químicos. Si 45% es Oxígeno, 19% Carbono, 26% Hidrógeno y 8% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;2%;95%;98%;3%;1
Encuentre el porcentaje correcto: Si un especialista gasta 22,5% de su salario en vivienda, 36,5% en comida, 8,5% en salud y 5,5% en educación, ¿de cuánto puede disponer para sus demás gastos? ;27%;84%;74%;15%;1
Calcule la respuesta correcta : Si una cama cuesta $350, un velador $75 y una silla $89, ¿cuánto debe pagarse por 4 camas, 12 veladores y 5 sillas? ;514;2745;1030;2700;2
Encuentra la respuesta correcta al planteamiento: Si un viaje individual a Colombia cuesta $800, uno a Miami $750 y uno a Italia $1250, ¿cuánto costaría a una pareja hacer los 3 viajes en un año? ;5800;5600;3760;1830;2
Selecciona la respuesta correcta al planteamiento: La nota final de Karen en Matemáticas es de 8.7 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 8.5 y en el segundo 7.9, ¿cuál fue su nota en el tercer examen? ;9.8;10;9.6;9.7;4
Calcular el valor correcto para el planteamiento: Un patio de autos tiene 150 unidades, el 40% de ellos son rojos y el 10% negros. ¿Cuántos autos de cada color hay? ;54 rojos y 6 negros;60 rojos y 5 negros ;54 rojos y 5 negros;60 rojos y 15 negros;4
"Calcular el valor correcto para el planteamiento: En el colegio ""Rockero"", a 60 de sus 100 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 120 estudiantes y a 30 les gusta la cumbia. En el colegio ""Cumbiero"" hay 200 estudiantes y a 130 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia? ";"""Cumbiero"" y ""Rockero"" ";"""Salsero""";"""Cumbiero"" ";"""Rockero""";3
Calcular el valor correcto al planteamiento: Los estudiantes aciertan en el 75% de las preguntas de una prueba nacional. Si la prueba tiene un total de 160 preguntas, en promedio, ¿en cuántas preguntas se espera que no acierten? ;60;90;65;40;4
Calcular el valor correcto para el planteamiento: El 20% de los anuncios en una ciudad son luminosos. Si en la ciudad hay 5400 anuncios, ¿cuántos anuncios no luminosos hay en toda la ciudad? ;3690;5220;80%;4320;4
Calcular el valor correcto al planteamiento: El ingreso mensual de un manager es de $1500. Al ascender a Coordinador, su sueldo aumentará 45%. ¿Cuál será su nuevo ingreso mensual? ;5426;1420;2175;1520;3
Calcular el valor correcto para el planteamiento: El ingreso promedio mensual de tres primos es de $2500. El mayor tiene un sueldo de $1800, el segundo gana $1500. ¿Cuál será el sueldo del hermano menor? ;3100;4200;2400;3000;2
Encuentra la respuesta correcta al planteamiento: Si Girasol=$5, Tulipán=$30, Palmera=$120, ¿cuántos tulipanes se pueden comprar por cada palmera? ;26;30;4;3;3
Encuentra la respuesta correcta al planteamiento: Los 2/5 de un número es 100, ¿cuánto será los 3/10 del mismo número? ;250;168;75;60;3
Encuentra la respuesta correcta al planteamiento: Se vendió un pantalón con una ganancia del 25% sobre el precio de costo. Si se ha vendido en $120, hallar el precio de costo. ;78;86;81;96;4
Encuentre la respuesta correcta: Si el dólar se devaluará cada año 6%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;78%;76%;84%;68%;3
Encuentre la respuesta correcta: Al adquirir un camión, cuyo precio es de $9000, nos hacen un descuento del 15%, ¿cuánto hay que pagar por el vehículo? ;6400;6500;7650;6399;3
Encuentra la respuesta correcta: Si 8 personas se comen 40 bocaditos en 15 minutos, ¿cuánto demorarán 10 personas en comer la misma cantidad? ;13;11;10;12;4
Encuentra la respuesta correcta: El 30% de 12 horas es equivalente en minutos a: ;360;216;3.6;306;2
Encuentra la respuesta correcta: El 40% de 120 semanas equivale a _____ días ;48;336;98;14;2
Encuentra la respuesta correcta al planteamiento: Si una motocicleta avanza a 160 km/h durante 54 minutos y luego a 70 km/h durante 30 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;210;179;197;120;2
Selecciona la respuesta correcta al planteamiento:Una persona camina durante 36 minutos a 5 km/h, luego pausa 3 minutos y corre otros 12 minutos a 25 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ;9;6;8;7;3
Selecciona la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 45 km/h y se detiene 8 minutos cada hora. Si circula durante 9 horas, ¿cuántos kilómetros recorre en ese tiempo? ;351;360;326;250;1
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 230 km/h y uno urbano lo hace a 120 km/h. Después de 6 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;630;256;660;330;3
Selecciona la respuesta correcta al planteamiento: En una jornada de 5 horas se pintan 20 metros cuadrados de pared y se emplean 2 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 60 metros cuadrados? ;15 horas y 7.5 litros de pintura;15 horas y 6 litros de pintura ;15 horas y 6.5 litros de pintura ;15 horas y 8.5 litros de pintura;2
Selecciona la respuesta correcta al planteamiento: El precio de un par de lámparas es de $2100 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 10%?;2310;1155;4200;4120;2
Selecciona la respuesta correcta al planteamiento: Se desea distribuir 550 esferos, 350 cuadernos, 300 libros y 1000 lápices entre 25 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?;22 esferos, 14 cuadernos, 10 libros y 37 lápices ;22 esferos, 14 cuadernos, 12 libros y 40 lápices;22 esferos, 14 cuadernos, 11 libros y 40 lápices ;23 esferos, 14 cuadernos, 10 libros y 36 lápices ;2
Encuentra la respuesta correcta al planteamiento: Enrique tiene el doble de ahorro que Carmen, si entre ambos desean comprar un auto de $14.000, Enrique debería tener el doble de dinero que tiene. ¿Cuánto dinero tiene Carmen? ;4000;2400;2000;3000;2
Calcular el valor correcto al planteamiento: Una persona tiene $350 en cinco cupones y cuatro de ellos son de $63 cada uno, ¿de cuánto es el otro cupón? ;$35;$49;$70;$52;1
Selecciona la respuesta correcta al planteamiento: Usted tiene 38 pelotas, regala 6, le roban 3, pierde 1 y compra otras 5. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 3 niños a los que debe entregar?;10;12;9;11;4
"Selecciona la respuesta correcta al planteamiento: En un día Luis corre 19 km, camina 7 km; nada 2800 metros más, conduce en bicicleta otros 5050 metros. ¿De cuántos kilómetros fue su recorrido? "; 33.85; 35.85; 35.8; 32.23;1
"Encuentra la respuesta correcta al planteamiento: En un hogar se utilizan 400 litros de agua, 190 litros se utilizan para bañarse, se lavan platos y ropa con 40 litros, se lavan los autos con el 6% y lo mismo se emplea en el jardín. ¿Cuántos litros se utilizan para el jardín? ";18;24;28;34;2
Encuentra la respuesta correcta al planteamiento: Una familia compra 130 quesadillas. El 40% de ellos eran de carne, el 30% eran de pollo y los demás de queso, ¿cuántos eran de queso? ;27;29;39;32;3
Encuentra la respuesta correcta al planteamiento: Para cenar, unos amigos piden 13 pizzas. Cada pizza tiene 6 rebanadas. Se comen el 63% en el restaurante, se llevan a casa el 27% y dejan lo demás. ¿Cuánto dejaron? ;13%;12%;90%;10%;4
Selecciona la respuesta correcta al planteamiento: Un auto avanza 19 kilómetros, luego retrocede 820 metros, vuelve a avanzar 2 kilómetros, y retrocede otros 50 metros ¿cuántos metros avanzó realmente? ;20130;12130;17130;19200;1
Encuentra la respuesta correcta al planteamiento: Una nave espacial, que puede viajar a 900 millas por hora, se mantiene en la base durante 9 horas desde las 04:00 am. Cuando despega, se desplaza a 750 millas por hora, ¿cuántas millas llevará recorridos a las 9:00 pm? ;6000;6750;7600;12750;1
Encuentra la respuesta correcta al planteamiento: Un avión hace 15 vuelos por mes. Cada mes, el piloto revisa 8 veces los controles, 7 los alerones, 12 el combustible. En seis meses, ¿cuántas veces habrá revisado los controles, los alerones y el combustible, respectivamente? ; 48, 42, 72; 55, 40, 45 ; 120, 105, 180; 90, 80, 110;3
Calcular el valor correcto para el planteamiento: Si Pedro tiene 13 años y su madre cinco veces la edad que ella. Cuando Pedro tenga 21 años, ¿cuántos tendrá su madre? ;73;59;72;82;1
Encuentra la respuesta correcta al planteamiento: Varias familias van de paseo en 10 autos. Cinco autos llevan familias de 6 personas cada uno. En tres autos viajan cinco personas y dos van ocupados por solo tres personas.  ¿Cuántas personas viajan en total? ;37;51;45;38;2
Encuentra el porcentaje correcto: Una espada está compuesta de 6 elementos: 17% de Zinc, 18% de Hierro, 21% de Carbono, 6% de magnesio y 33% de Estaño, ¿cuál será el porcentaje de Bronce que posee? ;14%;5%;4%;6%;2
Encuentre el porcentaje correcto: Diariamente, el 59% del transporte urbano va ocupado por hombres menores de 65 y el 26% por mujeres menores de 65. Del restante, 16% son mujeres, ¿qué porcentaje del total representan? ;65%; 2.4% ;8%; 3.4%;2
Encuntre el porcentaje correcto: Un compuesto químico está hecho de elementos químicos. Si 45% es Oxígeno, 18% Carbono, 12% Hidrógeno y 5% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;2%;15%;20%;93%;3
Encuentre el porcentaje correcto: Si un especialista gasta 32,5% de su salario en vivienda, 21,7% en comida, 18,3% en salud y 9.7% en educación, ¿de cuánto puede disponer para sus demás gastos? ; 16.23% ; 84.1% ; 17.8% ; 15.12%;3
Calcule la respuesta correcta: Si una cama cuesta $320, un velador $70 y una silla $710, ¿cuánto debe pagarse por 4 camas, 12 veladores y 5 sillas? ;2800;3320;1030;1830;1
Encuentra la respuesta correcta al planteamiento: Si un viaje individual a Esmeraldas cuesta $450, uno a Manta $580 y uno a Galápagos $890, ¿cuánto costaría a una pareja hacer los 3 viajes en un año? ;3660;3840;3760;1830;2
Selecciona la respuesta correcta al planteamiento: La nota final de Karen en Matemáticas es de 9.4 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 9.1 y en el segundo 9.8, ¿cuál fue su nota en el tercer examen? ;9.9;10;9.3;9.7;3
Calcular el valor correcto para el planteamiento: Un patio de autos tiene 130 unidades, el 30% de ellos son rojos y el 10% negros. ¿Cuántos autos de cada color hay? ; 39 rojos y 13 negros; 45 rojos y 12 negros ; 40 rojos y 13 negros; 35 rojos y 16 negros;1
"Calcular el valor correcto para el planteamiento: En el colegio ""Rockero"", a 40 de sus 80 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 60 estudiantes y a 15 les gusta la cumbia. En el colegio ""Cumbiero"" hay 100 estudiantes y a 70 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia? ";" ""Cumbiero"" y ""Rockero"" ";" ""Salsero""";" ""Cumbiero"" ";" ""Rockero""";3
Calcular el valor correcto al planteamiento: Los estudiantes aciertan en el 68% de las preguntas de una prueba nacional. Si la prueba tiene un total de 150 preguntas, en promedio, ¿en cuántas preguntas se espera que no acierten? ;45;39;48;32;3
Calcular el valor correcto para el planteamiento: El 20% de los anuncios en una ciudad son luminosos. Si en la ciudad hay 4500 anuncios, ¿cuántos anuncios no luminosos hay en toda la ciudad? ;3600;2810;8210;800;1
Calcular el valor correcto al planteamiento: El ingreso mensual de un manager es de $1300. Al ascender a Coordinador, su sueldo aumentará 25%. ¿Cuál será su nuevo ingreso mensual? ;1620;1420;1350;1625;4
Calcular el valor correcto para el planteamiento: El ingreso promedio mensual de tres primos es de $2000. El mayor tiene un sueldo de $1400, el segundo gana $1300. ¿Cuál será el sueldo del hermano menor? ;3100;3300;1900;3000;2
Encuentra la respuesta correcta al planteamiento: Si Flor=$3, Rosa=$9, Planta=$108, ¿cuántas rosas se pueden comprar por cada planta? ;14;27;12;3;3
Encuentra la respuesta correcta al planteamiento: Los 3/5 de un número es 60, ¿cuánto será los 3/10 del mismo número? ;100;30;32;60;2
Encuentra la respuesta correcta al planteamiento: Se vendió un pantalón con una ganancia del 10% sobre el precio de costo. Si se ha vendido en $110, hallar el precio de costo. ;88;80;100;98;3
Encuentre la respuesta correcta: Si el dólar se devaluará cada año 8%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;78%;76%;84%;68%;1
Encuentre la respuesta correcta: Al adquirir una lancha, cuyo precio es de $8400, nos hacen un descuento del 20%, ¿cuánto hay que pagar por el vehículo? ;7400;6720;7056;6399;2
Encuentra la respuesta correcta: Si 9 personas se comen 45 bocaditos en 12 minutos, ¿cuánto demorarán 12 personas en comer la misma cantidad? ;9;13;10;11;1
Encuentra la respuesta correcta: El 25% de 11 horas es equivalente en minutos a:;108;200;432;165;4
Encuentra la respuesta correcta: El 25% de 60 semanas equivale_______ a días:;20;105;98;14;2
Encuentra la respuesta correcta al planteamiento: Si una motocicleta avanza a 130 km/h durante 30 minutos y luego a 100 km/h durante 30 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;210;110;115;120;3
Selecciona la respuesta correcta al planteamiento: Una persona camina durante 45 minutos a 6 km/h, luego pausa 3 minutos y corre otros 10 minutos a 12 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ; 9.6; 6.5; 8.2; 7.2;2
Selecciona la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 70 km/h y se detiene 5 minutos cada hora. Si circula durante 8 horas, ¿cuántos kilómetros recorre en ese tiempo? ;400;560;440;513;4
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 160 km/h y uno urbano lo hace a 80 km/h. Después de 6 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;630;540;480;675;3
Selecciona la respuesta correcta al planteamiento: En una jornada de 8 horas se pintan 15 metros cuadrados de pared y se emplean 4 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 45 metros cuadrados? ; 20 horas y 7.5 litros de pintura; 24 horas y 8 litros de pintura ; 24 horas y 6.5 litros de pintura ; 24 horas y 12 litros de pintura;4
Selecciona la respuesta correcta al planteamiento: El precio de un par de lámparas es de $1300 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 14%?;741;600;662;744;1
Selecciona la respuesta correcta al planteamiento: Se desea distribuir 324 esferos, 486 cuadernos, 243 libros y 702 lápices entre 27 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?; 13 esferos, 14 cuadernos, 10 libros y 37 lápices ; 12 esferos, 18 cuadernos, 9 libros y 26 lápices; 12 esferos, 18 cuadernos, 9 libros y 27 lápices ; 12 esferos, 14 cuadernos, 10 libros y 36 lápices ;2
Encuentra la respuesta correcta al planteamiento: Luis tiene el triple de ahorro que Jorge, si entre ambos desean comprar un auto de $18.000, Luis debería tener el triple de dinero que tiene. ¿Cuánto dinero tiene Jorge? ;1800;2000;3000;4000;1
Calcular el valor correcto al planteamiento: Una persona tiene $340 en siete cupones y cinco de ellos son de $65 cada uno, ¿de cuánto son los otros dos cupones? ; $80; $15;$20;$32.5;2
Selecciona la respuesta correcta al planteamiento: Usted tiene 30 pelotas, regala 3, le roban 2, pierde 6 y compra otras 8. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 3 niños a los que debe entregar?;3;5;8;9;4
"Selecciona la respuesta correcta al planteamiento: En un día Luis corre 25 km, camina 5 km; nada 1000 metros más, conduce en bicicleta otros 8000 metros. ¿De cuántos kilómetros fue su recorrido? ";34;33;39;32;3
"Encuentra la respuesta correcta al planteamiento: En un hogar se utilizan 380 litros de agua, 120 litros se utilizan para bañarse, se lavan platos y ropa con 43 litros, se lavan los autos con el 9% y lo mismo se emplea en el jardín. ¿Cuántos litros se utilizan para el jardín? ";17;19;18;34;4
Encuentra la respuesta correcta al planteamiento: Una familia compra 200 quimbolitos. El 40% de ellos eran de carne, el 25% eran de pollo y los demás eran mixtos, ¿cuántos eran de mixtos? ;25;65;35;70;4
Encuentra la respuesta correcta al planteamiento: Una familia compra 200 quimbolitos. El 40% de ellos eran de carne, el 25% eran de pollo y los demás eran mixtos, ¿cuántos eran de mixtos? ;13%;85%;15%;88%;3
Selecciona la respuesta correcta al planteamiento: Un auto avanza 20 kilómetros, luego retrocede 500 metros, vuelve a avanzar 6 kilómetros, ¿cuántos metros avanzó realmente? ;18200.00;25500.00;25600.00;12750.00;1
Encuentra la respuesta correcta al planteamiento: Una nave espacial, que puede viajar a 1400 millas por hora, se mantiene en la base durante 7 horas desde las 03:00 am. Cuando despega, se desplaza a 800 millas por hora, ¿cuántas millas llevará recorridos a las 7:00 pm? ;6000;6750;7200;12750;3
Encuentra la respuesta correcta al planteamiento: Un avión hace 15 vuelos por mes. Cada mes, el piloto revisa 7 veces los controles, 5 los alerones, 11 el combustible. En seis meses, ¿cuántas veces habrá revisado los controles, los alerones y el combustible, respectivamente? ;42, 30, 55;42, 30, 66 ;42, 30, 69;42, 30, 110;2
Calcular el valor correcto para el planteamiento: Si María tiene 9 años y su padre cinco veces la edad que ella. Cuando Pedro tenga 27 años, ¿cuántos tendrá su madre? ;63;48;60;62;1
ncuentra la respuesta correcta al planteamiento: Varias familias van de paseo en 18 autos. Nueve autos llevan familias de 5 personas cada uno. En cinco autos viajan cuatro personas y cuatro van ocupados por solo dos personas.  ¿Cuántas personas viajan en total? ;69;73;70;38;2
Encuentra el porcentaje correcto: Una espada está compuesta de 5 elementos: 14% de Zinc, 20% de Hierro, 10% de Carbono y 8% de Estaño, ¿cuál será el porcentaje de Bronce que posee? ;47%;46%;50%;48%;4
Encuentre el porcentaje correcto: Diariamente, el 65% del transporte urbano va ocupado por hombres menores de 70 y el 5% por mujeres menores de 70. Del restante, 15% son mujeres, ¿qué porcentaje del total representan? ;5%;4.5% ;5.5% ;6%;2
Encuntre el porcentaje correcto: Un compuesto químico está hecho de elementos químicos. Si 55% es Oxígeno, 17% Carbono, 9% Hidrógeno y 5% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;2%;86%;14%;8%;3
Encuentre el porcentaje correcto: Si un especialista gasta 22,5% de su salario en vivienda, 36.5% en comida, 12.5% en salud y 5.5% en educación, ¿de cuánto puede disponer para sus demás gastos;16%;77%;23%;22%;3
Calcule la respuesta correcta: Si una almario cuesta $200, una cómoda $100 y una mesa $300, ¿cuánto debe pagarse por 5 almarios, 8 cómodas y 4 mesas? ;2600;3050;2000;3000;4
Encuentra la respuesta correcta al planteamient: Si un viaje individual a Montañita cuesta $350, uno a Manabí $250 y uno a Atacames $420, ¿cuánto costaría a una pareja hacer los 3 viajes en un año? ;2040;2600;2000;2500;1
Selecciona la respuesta correcta al planteamiento: La nota final de Karen en Matemáticas es de 9.3 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 9.4 y en el segundo 8.8, ¿cuál fue su nota en el tercer examen? ;9.9;10;9.6;9.7;4
Calcular el valor correcto para el planteamiento: Un patio de autos tiene 240 unidades, el 55% de ellos son plateados y el 10% blancos. ¿Cuántos autos de cada color hay? ;132 plateados y 6 blancos;132 plateados y 25 blancos;132 plateados y 24 blancos;132 plateados y 55 blancos;3
"Calcular el valor correcto para el planteamiento: En el colegio ""Rockero"", a 80 de sus 100 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 50 estudiantes y a 35 les gusta la cumbia. En el colegio ""Cumbiero"" hay 150 estudiantes y a 70 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia? ";"""Cumbiero"" y ""Rockero"" ";"""Salsero""";"""Cumbiero"" ";"""Rockero""";4
Calcular el valor correcto al planteamiento: Los estudiantes aciertan en el 60% de las preguntas de una prueba nacional. Si la prueba tiene un total de 180 preguntas, en promedio, ¿en cuántas preguntas se espera que no acierten? ;104;72;65;73;2
Calcular el valor correcto para el planteamiento: El 45% de los anuncios en una ciudad son luminosos. Si en la ciudad hay 5100 anuncios, ¿cuántos anuncios no luminosos hay en toda la ciudad? ;2805;2810;60%;400;1
Calcular el valor correcto al planteamiento: El ingreso mensual de un Doctor es de $1500. Al ascender a Coordinador, su sueldo aumentará 50%. ¿Cuál será su nuevo ingreso mensual? ;1620;1420;2260;2250;4
Calcular el valor correcto para el planteamiento: El ingreso promedio mensual de cuatro hermanos es de $2200. La hermana mayor tiene un sueldo de $1700, la segunda gana $1100 y la tercera gana $1200 ¿Cuál será el sueldo de la hermana menor? ;3000;4800;4900;3000;2
Encuentra la respuesta correcta al planteamient: Si Geranios=$5, Margaritas=$25, Dalia=$100, ¿cuántas margaritas se pueden comprar por cada dalias? ;6;3;4;20;3
Encuentra la respuesta correcta al planteamiento: Los 4/5 de un número es 100, ¿cuánto será los 7/10 del mismo número? ;87.5;87;86;78;1
Encuentra la respuesta correcta al planteamiento: Se vendió una blusa con una ganancia del 20% sobre el precio de costo. Si se ha vendido en $60, hallar el precio de costo. ;78;80;50;68;3
Encuentre la respuesta correcto: Si el dólar se devaluará cada año 8%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;78%;76%;84%;68%;1
Encuentre la respuesta correcta: Al adquirir un yate, cuyo precio es de $9500, nos hacen un descuento del 40%, ¿cuánto hay que pagar por el vehículo? ;5700;5800;8020;6399;1
Encuentra la respuesta correcta: Si 10 personas se comen 50 bocaditos en 18 minutos, ¿cuánto demorarán 15 personas en comer la misma cantidad? ;10;12;13;14;2
Encuentra la respuesta correcta: El 15% de 11 horas es equivalente en minutos a: ;108;99;109;432;2
Encuentra la respuesta correcta: El 25% de 80 semanas equivale a _____ días ;120;196;140;104;3
Encuentra la respuesta correcta al planteamiento: Si una motocicleta avanza a 130 km/h durante 20 minutos y luego a 100 km/h durante 50 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;210;170;126;102;3
Selecciona la respuesta correcta al planteamiento: Una persona camina durante 40 minutos a 12 km/h, luego pausa 5 minutos y corre otros 15 minutos a 8 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ;2;11;10;8;3
Selecciona la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 90 km/h y se detiene 8 minutos cada hora. Si circula durante 11 horas, ¿cuántos kilómetros recorre en ese tiempo? ;433;432;466;858;4
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 140 km/h y uno urbano lo hace a 70 km/h. Después de 6 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;420;240;70;425;1
Selecciona la respuesta correcta al planteamiento: En una jornada de 7 horas se pintan 20 metros cuadrados de pared y se emplean 3.5 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 60 metros cuadrados? ;20 horas y 7.5 litros de pintura;21 horas y 8 litros de pintura ;21 horas y 10.5 litros de pintura ;24 horas y 8.5 litros de pintura;3
Selecciona la respuesta correcta al planteamiento: El precio de un par de lámparas es de $1800 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 13%?;372;1017;1016;1000;2
Selecciona la respuesta correcta al planteamiento: Se desea distribuir 360 esferos, 480 cuadernos, 280 libros y 920 lápices entre 40 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?;9 esferos, 12 cuadernos, 10 libros y 23 lápices ;9 esferos, 14 cuadernos, 10 libros y 23 lápices;13 esferos, 14 cuadernos, 7 libros y 37 lápices ;9 esferos, 12 cuadernos, 7 libros y 23 lápices ;4
Encuentra la respuesta correcta al planteamiento: Vinicio tiene el doble de ahorro que Erika, si entre ambos desean comprar un auto de $24.500, Vinicio debería tener el triple de dinero que tiene. ¿Cuánto dinero tiene Erika? ;3400;1000;4000;3500;4
Calcular el valor correcto al planteamiento: Una persona tiene $350 en cinco cupones y cuatro de ellos son de $55 cada uno, ¿de cuánto son los otros dos cupones? ;$180;$135;$120;$130;4
Selecciona la respuesta correcta al planteamiento: Usted tiene 18 pelotas, regala 2, le roban 4, pierde 6 y compra otras 8. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 2 niños a los que debe entregar?;7;6;5;2;1
"Selecciona la respuesta correcta al planteamiento: En una competencia corre 17 km, camina 8 km; nada 3000 metros más, conduce en bicicleta otros 3000 metros. ¿De cuántos kilómetros fue su recorrido? ";34;33;31;32;3
"Encuentra la respuesta correcta al planteamiento: En un hogar se utilizan 340 litros de agua, 190 litros se utilizan para bañarse, se lavan platos y ropa con 34 litros, se lavan los autos con el 10% y lo mismo se emplea en el jardín. ¿Cuántos litros se utilizan para el jardín? ";17;34;36;38;2
Encuentra la respuesta correcta al planteamiento: Una familia compra 100 tacos. El 38% de ellos eran de carne, el 28% eran de pollo y los demás eran de queso, ¿cuántos eran de queso? ;23;36;34;32;3
Encuentra la respuesta correcta al planteamiento: Para cenar, unos amigos piden 7 pizzas. Cada pizza tiene 8 rebanadas. Se comen el 47% en el restaurante, se llevan a casa el 25% y dejan lo demás. ¿Cuánto dejaron? ;13%;28%;72%;88%;2
Selecciona la respuesta correcta al planteamiento: Un auto avanza 15 kilómetros, luego retrocede 1000 metros, vuelve a avanzar 3 kilómetros, ¿cuántos metros avanzó realmente? ;18200;25500;17000;12750;3
Encuentra la respuesta correcta al planteamiento: Una nave espacial, que puede viajar a 900 millas por hora, se mantiene en la base durante 8 horas desde las 04:00 am. Cuando despega, se desplaza a 750 millas por hora, ¿cuántas millas llevará recorridos a las 9:00 pm? ;6000;6750;7200;12750;2
Encuentra la respuesta correcta al planteamiento: Un avión hace 10 vuelos por mes. Cada mes, el piloto revisa 9 veces los controles, 8 los alerones, 11 el combustible. En cuatro meses, ¿cuántas veces habrá revisado los controles, los alerones y el combustible, respectivamente? ; 36, 32, 44; 55, 40, 45 ; 45, 55, 40; 90, 80, 110;1
Calcular el valor correcto para el planteamiento: Si Pedro tiene 15 años y su madre cuatro veces la edad que ella. Cuando Pedro tenga 20 años, ¿cuántos tendrá su madre? ;59;48;65;92;3
Encuentra la respuesta correcta al planteamiento: Varias familias van de paseo en 12 autos. Cinco autos llevan familias de 5 personas cada uno. En tres autos viajan cuatro personas y cuatro van ocupados por solo dos personas.  ¿Cuántas personas viajan en total? ;57;36;45;38;3
Encuentra el porcentaje correcto: Una espada está compuesta de 5 elementos: 17% de Zinc, 28% de Hierro, 7% de Carbono y 20% de Estaño, ¿cuál será el porcentaje de Bronce que posee? ;43%;38%;28%;18%;3
Encuentre el porcentaje correcto: Diariamente, el 45% del transporte urbano va ocupado por hombres menores de 65 y el 30% por mujeres menores de 65. Del restante, 20% son mujeres, ¿qué porcentaje del total representan? ;5%;16%;10%;15%;1
Encuntre el porcentaje correcto: El cuerpo humano está hecho de elementos químicos. Si 68% es Oxígeno, 17% Carbono, 11% Hidrógeno y 2% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;2%;95%;98%;3%;1
Encuentre el porcentaje correcto: Si un profesional gasta 28% de su salario en vivienda, 18% en comida, 16.5% en salud y 8.5% en educación, ¿de cuánto puede disponer para sus demás gastos?;71%;84%;29%;15%;3
Calcule la respuesta correcta: Si una cama cuesta $100, un velador $60 y una silla $70, ¿cuánto debe pagarse por 4 camas, 2 veladores y 6 sillas? ;980;950;940;850;3
Encuentra la respuesta correcta al planteamiento: Si un viaje individual a Esmeraldas cuesta $300, uno a Manta $500 y uno a Galápagos $850, ¿cuánto costaría a una pareja hacer los 3 viajes en un año? ;3660;3560;3300;1830;3
Selecciona la respuesta correcta al planteamiento: La nota final de juan en Matemáticas es de 9.3 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 9.0 y en el segundo 9.4, ¿cuál fue su nota en el tercer examen? ;9.9;10;9.5;9.7;3
Calcular el valor correcto para el planteamiento: Un patio de autos tiene 120 unidades, el 50% de ellos son rojos y el 10% negros. ¿Cuántos autos de cada color hay? ; 54 rojos y 6 negros; 62 rojos y 10 negros; 60 rojos y 12 negros; 45 rojos y 6 negros;3
"Calcular el valor correcto para el planteamiento: En el colegio ""Rockero"", a 40 de sus 80 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 60 estudiantes y a 45 les gusta la cumbia. En el colegio ""Cumbiero"" hay 100 estudiantes y a 30 les gusta la cumbia. ¿En qué colegio hay menor porcentaje de gusto por la cumbia? ";" ""Cumbiero"" y ""Rockero"" ";" ""Salsero""";" ""Cumbiero"" ";" ""Rockero""";2
Calcular el valor correcto al planteamiento: Los estudiantes aciertan en el 70% de las preguntas de una prueba nacional. Si la prueba tiene un total de 180 preguntas, en promedio, ¿en cuántas preguntas se espera que no acierten? ;64;54;34;40;2
Calcular el valor correcto para el planteamiento: El 30% de los anuncios en una ciudad son luminosos. Si en la ciudad hay 4500 anuncios, ¿cuántos anuncios no luminosos hay en toda la ciudad? ;3690;810;82%;3150;4
Calcular el valor correcto al planteamiento: El ingreso mensual de un especialista es de $1250. Al ascender a Coordinador, su sueldo aumentará 40%. ¿Cuál será su nuevo ingreso mensual? ;1250;1540;1650;1750;4
Calcular el valor correcto para el planteamiento: El ingreso promedio mensual de tres hermanos es de $2000. La hermana mayor tiene un sueldo de $1400, la segunda gana $2400 ¿Cuál será el sueldo de la hermano menor? ;3100;2200;1900;3000;2
Encuentra la respuesta correcta al planteamiento: Si Flor=$3, Rosa=$27, Planta=$54, ¿cuántas rosas se pueden comprar por cada planta? ;6;3;2;20;3
Encuentra la respuesta correcta al planteamiento: Los 2/5 de un número es 100, ¿cuánto será los 3/10 del mismo número? ;200;168;80;75;4
Encuentra la respuesta correcta al planteamiento: Se vendió una camisa con una ganancia del 20% sobre el precio de costo. Si se ha vendido en $84, hallar el precio de costo. ;78;80;81;70;4
Encuentre la respuesta correcta: Si el dólar se devaluará cada año 6%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;78%;76%;84%;68%;3
Encuentre la respuesta correcta: Al adquirir una lancha, cuyo precio es de $6000, nos hacen un descuento del 20%, ¿cuánto hay que pagar por el vehículo? ;4200;4000;4800;4250;3
Encuentra la respuesta correcta: Si 10 personas se comen 40 bocaditos en 16 minutos, ¿cuánto demorarán 8 personas en comer la misma cantidad? ;10;15;20;17;2
Encuentra la respuesta correcta: El 30% de 8 horas es equivalente en minutos a: ;108;144;96;432;2
Encuentra la respuesta correcta: El 40% de 70 semanas equivale a _____ días ;20;196;98;146;2
Encuentra la respuesta correcta al planteamiento: Si una motocicleta avanza a 120 km/h durante 20 minutos y luego a 90 km/h durante 40 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;210;110;100;120;3
Selecciona la respuesta correcta al planteamiento: Una persona camina durante 50 minutos a 6 km/h, luego pausa 3 minutos y corre otros 40 minutos a 6 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo?;8;6;9;7;3
Selecciona la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 50 km/h y se detiene 6 minutos cada hora. Si circula durante 8 horas, ¿cuántos kilómetros recorre en ese tiempo? ;400;360;340;376;2
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 140 km/h y uno urbano lo hace a 60 km/h. Después de 5 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;630;400;450;500;2
Selecciona la respuesta correcta al planteamiento: En una jornada de 10 horas se pintan 18 metros cuadrados de pared y se emplean 3 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 45 metros cuadrados? ; 25 horas y 7.5 litros de pintura; 80 horas y 8 litros de pintura ; 40 horas y 6.5 litros de pintura ; 24 horas y 8.5 litros de pintura;1
Selecciona la respuesta correcta al planteamiento: El precio de un par de lámparas es de $1800 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 12%?;1008;1000;900;980;1
Selecciona la respuesta correcta al planteamiento: Se desea distribuir 312 esferos, 336 cuadernos, 264 libros y 456 lápices entre 12 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?; 23 esferos, 24 cuadernos, 10 libros y 37 lápices ; 26 esferos, 28 cuadernos, 22 libros y 38 lápices; 25 esferos, 24 cuadernos, 19 libros y 37 lápices ; 23 esferos, 24 cuadernos, 10 libros y 36 lápices ;2
Encuentra la respuesta correcta al planteamiento: Luis tiene el doble de ahorro que Jorge, si entre ambos desean comprar un auto de $14.000, Luis debería tener el triple de dinero que tiene. ¿Cuánto dinero tiene Jorge? ;2400;2000;3000;4000;2
Calcular el valor correcto al planteamiento: Una persona tiene $380 en ocho cupones y siete de ellos son de $45 cada uno, ¿de cuánto es el otro cupón? ;$25 ;$50;$65;$85;3
Selecciona la respuesta correcta al planteamiento: Usted tiene 50 tarjetas, compra 6, le regalan 4, pierde 10 y le roban 6. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 11 niños a los que debe entregar?;3;2;4;1;3
"Selecciona la respuesta correcta al planteamiento: En un día Luis escala 1600 metros, camina 2 km al día siguiente; y avanza  2500 metros más el último día. ¿Cuántos metros ha escalado?";5000;6100;6000;4500;2
"Encuentra la respuesta correcta al planteamiento: En una lavadora de autos se usan 220 litros de agua, 120 litros se utilizan para los camiones, se lavan autos con 50 litros, se lavan las motos con el 10% del restante. ¿Cuántos litros se utilizan para para las motos? ";22;10;5;50;3
Encuentra la respuesta correcta al planteamiento: El jefe repartirá 100 emparedados. El 36% de ellos son simples, el 40% son dobles y los demás son triples, ¿cuántos eran triples? ;23;77;24;25;3
Encuentra la respuesta correcta al planteamiento: Para una fiesta, unos amigos piden 10 paquetes de refrescos. Cada paquete tiene 12 latas. Se toman el 80%. ¿Cuántas dejaron? ;4;12;24;88;3
Selecciona la respuesta correcta al planteamiento:Un cohete asciende 4.6 kilómetros, luego desciende 3200 metros y explota, ¿cuántos metros le falto para llegar al piso nuevamente? ;4000;4200;1400;3600;3
Encuentra la respuesta correcta al planteamiento: Un yate, que puede viajar a 500 millas por hora, se mantiene en el muelle durante 6 horas desde las 02:00 am. Cuando zarpa, se desplaza a 350 millas por hora, ¿cuántas millas llevará recorridos a las 5:00 pm? ;1750;1050;3150;1500;3
Encuentra la respuesta correcta al planteamiento: Un inspector hace 12 visitas por mes. Cada mes, el entrega 6 reportes, 7 los resúmenes, 11 carpetas. En seis meses, ¿cuantos reportes, resúmenes, carpetas habrá entregado respectivamente? ; 36, 42, 66; 36, 42, 45 ; 36, 42, 60; 40, 80, 70;1
Calcular el valor correcto para el planteamiento: Si Pablo tiene 30 años y su hijo la quinta parte. Cuando Pablo tenga 35 años, ¿cuántos tendrá su hijo? ;6;5;35;11;4
"Encuentra la respuesta correcta al planteamiento: En un patio de autos hay cuatro camiones de 8 ruedas; tres buses de 6 ruedas; 4 automóviles de 4 ruedas y hay 2 motocicletas Tres autos llevan familias de 5 personas cada uno. ¿Cuántas ruedas hay en total? ";64;66;70;72;3
Encuentra el porcentaje correcto: Para una mezcla de pintura se ha usado 5 colores: 22% de roja, 16% de blanco, 8% de rosa y 5% de café, ¿cuál será el porcentaje de agua que posee la mezcla? ;43%;57%;47%;49%;4
Encuentre el porcentaje correcto: En un experimento, el 40% de individuos son hombres  mayores de edad, el 25% de mujeres también son mayores de edad. Del restante el 20% son hombres, ¿qué porcentaje del total representan? ;5%; 1.4% ;7%;35%;3
Encuntre el porcentaje correcto: Para la elaboración de un antioxidante se usó 32% es Oxígeno, 23% sodio, 14% Hidrógeno y 12% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;19%;81%;98%;3%;1
Encuentre el porcentaje correcto: Si un inversionista coloca 16,5% de su salario en la compañía A, 17,5% en la B, 7,5% en la C y 5,5% en la compañía D, ¿de cuánto puede disponer para sus demás inversiones? ;47%;84%;74%;53%;4
Calcule la respuesta correcta: Si una camisa cuesta $50, un pantalón $25 y una chompa $72, ¿cuánto debe pagarse por 4 camisas, 6 pantalones y 3 chompas? ;514;566;1030;560;2
Encuentra la respuesta correcta al planteamiento: Si un seguro de vida establece. Hospitalización por $400, servicio de ambulancia  $250 y medicinas por 130, ¿cuánto costaría a una pareja los 3 servicios del seguro de vida completo? ;780;1560;1650;1830;2
Selecciona la respuesta correcta al planteamiento: Luis requiere obtener un promedio de nota final de 9.0 para el ingreso al instituto, hasta el momento ha obtenido 8.5 en un aporte y 9.2 en el segundo, ¿cuál debería ser su nota en el tercer aporte? ;9.8;10;9.6;9.3;4
Calcular el valor correcto para el planteamiento: Un hotel tiene 180 habitaciones, el 30% de estas son simples y el 45% dobles. ¿Cuántas habitaciones hay de cada una? ; 54 rojos y 74 negros; 60 rojos y 5 negros ; 54 rojos y 5 negros; 54 rojos y 81 negros;4
"Calcular el valor correcto para el planteamiento: En el coliseo ""General"", a 80 de sus 160 asientos estan numerados. En el coliseo ""Alterno"" hay 200 asientos y 40 estan numerados. En el coliseo ""Comunitario"" hay 180 asientos y 80 estan numerados. ¿En qué coliseo hay menor porcentaje de asientos numerados? ";" ""General"" y ""Alterno"" ";" """"General""""";" ""Alterno"" ";" ""Comunitario""";2
Calcular el valor correcto al planteamiento: En un laboratorio en el 65% de las pruebas realizadas son de embarazo. Si el laboratorio realiza un promedio de 140 pruebas, en promedio, ¿cuántas pruebas no son de embarazo? ;91;90;65;49;4
Calcular el valor correcto para el planteamiento: El 12% de los semáforos de la ciudad estan dañados. Lo que quiere decir hay 960 semáforos dañados, ¿cuántos semáforos hay en total en la ciudad? ;4500;1075;80%;8000;4
Calcular el valor correcto al planteamiento: El ingreso mensual de un profesional es de $1200. Al ascender a Coordinador, su sueldo aumentará a 1440. ¿Cuál será el porcentaje de aumento? ;25%;10%;20%;120%;3
Calcular el valor correcto para el planteamiento: El registro promedio mensual de cuatro valores de temperatura es 12 ºC. El mayor registro es de14 ºC, el segundo valor es de 10 ºC. ¿Cuál será el otro valor registrado? ; 14 ºC ; 12 ºC ; 15 ºC; 10 ºC;2
Encuentra la respuesta correcta al planteamiento: Si esfero=$6, lápiz=$54, borrador=$84, ¿cuántos esferos se pueden comprar por cada borrador? ;20;16;14;13;3
Encuentra la respuesta correcta al planteamiento: Los 2/5 de los 5/4 de un número es 100, ¿cuánto será los 3/5 del mismo número? ;60;150;120;80;3
Encuentra la respuesta correcta al planteamiento: Se desea obtener una ganancia del 35% sobre el precio de costo. Si el precio es de $120, hallar el precio al que se debería vender. ;42;140;170;162;4
Encuentre la respuesta correcta: El recio de mi auto se devalúa 4% cada año ¿Qué porcentaje de su valor inicial en 2021 tendrá al finalizar el año 2023? ;78%;76%;88%;89%;4
Encuentre la respuesta correcta: Al adquirir una casa, cuyo precio es de $32000, nos hacen un descuento del 16%, ¿cuánto hay que pagar por el vehículo? ;18000;35200;26880;5120;2
Encuentra la respuesta correcta: Si 6 obreros cercan 100 metros en 35 minutos, ¿cuánto demorarán 2 obreros en cercar lo mismo? ;130;110;80;105;3
Encuentra la respuesta correcta: El 40% de 20 minutos es equivalente en segundos a: ;360;480;300;160;2
Encuentra la respuesta correcta: El 60% de 10 días equivale a _____ hora ;480;144;98;140;2
Encuentra la respuesta correcta al planteamiento: Si una avioneta avanza a 180 km/h durante 30 minutos y luego a 60 km/h durante 40 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;210;130;197;120;2
Selecciona la respuesta correcta al planteamiento: Un tren recorre durante 40 minutos a 12 km/h, luego se avería 8 minutos y por ultimo recorre otros 12 minutos a  25 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ;8;16;13;7;3
Selecciona la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 50 km/h y se detiene 30 minutos para cargar gasolina, ¿cuántos kilómetros recorre en 6 horas de trayecto? ;275;360;320;250;1
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 130 km/h y otro lo hace a 80 km/h en dirección contraria. Después de 5 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;250;1000;1050;850;3
Selecciona la respuesta correcta al planteamiento: En una jornada de 8 horas se preparan 24 pasteles y se emplean 4 litros de leche, ¿cuántas horas y cuántos litros se requerirá para preparar 12 pasteles? ; 4 horas y 4 litros de leche; 4 horas y 2 litros de leche ; 8 horas y 6 litros de leche; 10 horas y 8 litros de leche;2
Selecciona la respuesta correcta al planteamiento: El precio de un par de máquinas es de $8400 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 8%?;4000;4536;4200;4120;2
Selecciona la respuesta correcta al planteamiento: Se desea repartir 600 chocolates, 250 paletas, 225 chupetes y 100 caramelos entre 25 niños en forma equitativa, ¿cuántos chocolates, 'paletas, chupetes y caramelos les tocaría a cada uno?; 24 chocolates, 12 paletas, 8 chupetes y 4 caramelos; 24 chocolates, 10 paletas, 9 chupetes y 4 caramelos; 25 chocolates, 12 paletas, 9 chupetes y 4 caramelos; 20 chocolates, 12 paletas, 8 chupetes y 6 caramelos;2
Encuentra la respuesta correcta al planteamiento: Pedro tiene el triple de ahorro que Luis, si entre ambos desean comprar una moto de $5.600, Pedro debería tener el doble de dinero que tiene. ¿Cuánto dinero tiene Luis? ;a) 400 ;b) 800;c) 1800 ;d) 1400;2
Calcular el valor correcto al planteamiento: Una persona va comprar un auto de 1600 en cinco cuotas y cuatro de ellas son de  $300 cada una, ¿de cuánto es la última cuota? ;$800;$150;$200;$400;4
Selecciona la respuesta correcta al planteamiento: Usted tiene 45 tarjetas, regala 13, le roban 5, pierde 10 y compra otras 12. Si divide en partes iguales, ¿cuántas pelotas recibirán cada uno de los 3 niños a los que debe entregar?;3;5;8;9;4
"Selecciona la respuesta correcta al planteamiento: En un día Pablo corre 1200 km, camina 5 km; nada 2.5 km más, conduce en bicicleta otros 6000 metros. ¿De cuántos kilómetros fue su recorrido? ";34.0;14.7;12.5;20;2
"Encuentra la respuesta correcta al planteamiento: Para limpiar un estadio se usan 450 litros de agua, 260 litros se utilizan para las gradas, se lavan baños y camerinos con 120 litros, el parqueadero con el 8% y lo mismo se emplea en la cancha. ¿Cuántos litros se utilizan para la cancha? ";17;19;18;36;4
Encuentra la respuesta correcta al planteamiento: Un jefe compra 240 pasteles. El 55% de ellos eran de vainilla, el 15% eran de chocolate y los demás eran mixtos, ¿cuántos eran de fresa? ;25;65;35;72;4
Encuentra la respuesta correcta al planteamiento: Para desayunar, unos amigos piden 10 paquetes de galletas. Cada paquete contiene 12 galletas. Se comen el 45% en la oficina, se llevan a casa el 15% y dejan lo demás. ¿Cuánto dejaron? ;13%;40%;15%;60%;2
Selecciona la respuesta correcta al planteamiento: Un camión avanza 13 kilómetros, luego retrocede 800 metros, vuelve a avanzar 5 kilómetros, ¿cuántos metros le faltan para llegar a su destino a 18000 metros? ;18800;17200;800;12750;3
Encuentra la respuesta correcta al planteamiento: Un avión, puede alcanzar una velocidad de 680 km/h, se mantiene en el aeropuerto durante 6 horas desde las 02:00 am. Cuando despega, se desplaza a 240 millas por hora, ¿cuántas millas llevará recorridos a las 5:00 pm? ;2560;6750;7200;2160;4
.- Encuentra la respuesta correcta al planteamiento: Un barco hace 15 cruceros por mes. Cada mes, visita 6 veces Centroamérica, 4 los Europa, 12 el Asia. En seis meses, ¿cuántas veces habrá visitado Centroamérica, Europa y Asia, respectivamente? ; 24, 36, 72; 36, 24, 72 ; 42, 24, 72; 72, 30, 24;2
Calcular el valor correcto para el planteamiento: Si Lucia tiene 12 años y su padre cinco veces la edad que ella. Cuando Lucia tenga 26 años, ¿cuántos tendrá su padre? ;63;74;84;62;2
Encuentra la respuesta correcta al planteamiento: Varios niños van de excursión en 12 buses. Tres buses llevan de 12 niños cada uno. En cinco buses viajan seis niños y cuatro van ocupados por solo cuatro niños.  ¿Cuántos niños viajan en total? ;69;73;82;90;3
Encuentra el porcentaje correcto: Una batería está hecho de 5 elementos: 16% de Zinc, 25% de Hierro, 11% de Cobre y 9% de plomo, ¿cuál será el porcentaje de Bronce que posee? ;47%;35%;50%;39%;4
Encuentre el porcentaje correcto: Diariamente, el 40% del transporte urbano va ocupado por niños menores de 12 y el 20% por niñas menores de 12. Del restante, 25% son mujeres, ¿qué porcentaje del total representan? ;5%;60%; 5.5% ;10%;4
Encuntre el porcentaje correcto: Un tanque de un gas contiene distintos elementos químicos. Si 45% es Oxígeno, 16% Carbono, 7% Hidrógeno y 4% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;2%;28%;14%;8%;2
Encuentre el porcentaje correcto: Si un profesional gasta 36% de su salario en vivienda, 25% en comida, 13% en salud y 6% en educación, ¿de cuánto puede disponer para sus demás gastos? ;16%;20%;23%;22%;2
Calcule la respuesta correcta : Si una cama cuesta $300, una cómoda $200 y un par de lámparas lámpara $150, ¿cuánto debe pagarse por 4 camas, 7 cómodas y una lámpara? ;2655;2750;2675;3000;3
Encuentra la respuesta correcta al planteamiento: Si un viaje individual a Montañita cuesta $250, uno a Manabí $150 y uno a Atacames $320, ¿cuánto costaría a una pareja hacer los 3 viajes en un año? ;2040;1640;2000;1440;4
Selecciona la respuesta correcta al planteamiento: El tiempo final marcado por un nadador es 10.5 segundos y se calcula como el promedio de los tres tiempos hechos. Si en el primer tiempo obtuvo 10.6 y en el segundo 11.6, ¿cuál fue su nota en el tercer examen? ;9.9; 9.3 ;9.6;9.7;2
Calcular el valor correcto para el planteamiento: Una zapatería tiene 300 unidades, el 55% de ellos son casuales y el 15% deportivos. ¿Cuántos zapatos de cada uno hay? ; 165 casuales y 40 deportivos; 185 casuales y 40 deportivos; 165 casuales y 45 deportivos; 190 casuales y 60 deportivos;3
"Calcular el valor correcto para el planteamiento: En el colegio ""Rockero"", a 60 de sus 180 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 50 estudiantes y a 25 les gusta la cumbia. En el colegio ""Cumbiero"" hay 160 estudiantes y a 40 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia? ";" ""Cumbiero"" y ""Rockero"" ";" ""Salsero""";" ""Cumbiero"" ";" ""Rockero""";2
Calcular el valor correcto al planteamiento: Los votantes apoyan en un 40% a un candidato a nivel nacional. Si hubo un total de 1200 votos, en promedio, ¿en cuántas personas se espera que no apoyaran a ese candidato? ;104;720;650;730;2
Calcular el valor correcto para el planteamiento: El 25% de los restaurantes en una ciudad son vegetarianos. Si en la ciudad hay 450 restaurantes vegetarianos, ¿cuántos restaurantes hay en toda la ciudad? ;2805;2810;1800;4000;3
Calcular el valor correcto al planteamiento: El ingreso mensual de un abogado es de $1600. Al ascender  de puesto, su sueldo aumentará 15%. ¿Cuál será su nuevo ingreso mensual? ;1620;1420;2260;1840;4
Calcular el valor correcto para el planteamiento: El ingreso promedio mensual de tres socios es de $2100. El socio mayoritario tiene un ingreso de $1800, la segunda de $2100 ¿Cuál será el ingreso del tercer socio? ;3000;2400;4900;3000;2
Encuentra la respuesta correcta al planteamiento: Si carpeta=$6, cuaderno=$18, libro=$54, ¿cuántas carpetas se pueden comprar por cada libro? ;6;8;4;9;4
Encuentra la respuesta correcta al planteamiento: Los 2/5 de un número es 150, ¿cuánto será los 2/10 del mismo número? ;75;87;86;78;1
Encuentra la respuesta correcta al planteamiento: Se vendió una televisión con una ganancia del 25% sobre el precio de costo. Si se ha vendido en $160, hallar el precio de costo. ;138;140;150;128;4
Encuentre la respuesta correcta: Si el dólar se devaluará cada año 4%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;78%;88%;84%;68%;2
Encuentre la respuesta correcta: Al comprar una moto, cuyo precio es de $2500, nos hacen un descuento del 30%, ¿cuánto hay que pagar por el vehículo? ;1950;2100;1800;1750;4
Encuentra la respuesta correcta: Si 8 obreros arman 50 metros de pared en 35 minutos, ¿cuánto demorarán 14 obreros en comer la misma cantidad? ;10;12;20;14;3
Encuentra la respuesta correcta: El 20% de 2 horas es equivalente en segundos a: ;1080;2400;1000;1440;4
Encuentra la respuesta correcta: El 40% de 40 semanas equivale a _____ meses ;12;6;10;4;4
Encuentra la respuesta correcta al planteamiento: Si una moto avanza a 80 km/h durante 45 minutos y luego a 150 km/h durante 60 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;210;170;126;102;1
Selecciona la respuesta correcta al planteamiento: Una persona camina durante 120 minutos a 18 km/h, luego pausa 6 minutos y corre otros 25 minutos a 48 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ;28;50;48;56;4
Selecciona la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 60 km/h y se detiene 6 minutos cada hora. Si circula durante 8 horas, ¿cuántos kilómetros recorre en ese tiempo? ;433;432;466;858;2
Selecciona la respuesta correcta al planteamiento: Una moto de carreras va a una velocidad de 120 km/h y un auto lo hace a 90 km/h. Después de 4 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;420;240;120;425;3
Selecciona la respuesta correcta al planteamiento: En una jornada de 5 horas se pintan 50 metros cuadrados de pared y se emplean 6 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 70 metros cuadrados? ; 8 horas y 7.5 litros de pintura; 11 horas y 8 litros de pintura ; 10 horas y 8.4 litros de pintura ; 7 horas y 8.4 litros de pintura;4
Selecciona la respuesta correcta al planteamiento: El precio de un par de floreros es de $800 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 15%?;200;520;490;460;4
Selecciona la respuesta correcta al planteamiento: Se desea distribuir 288 esferos, 384 cuadernos, 216 libros y 552 lápices entre 24 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?; 12 esferos, 16 cuadernos, 9 libros y 23 lápices ; 16 esferos, 14 cuadernos, 10 libros y 23 lápices; 13 esferos, 14 cuadernos, 7 libros y 37 lápices ; 12 esferos, 16 cuadernos, 7 libros y 23 lápices ;1
Encuentra la respuesta correcta al planteamiento: Luis tiene el mismo de ahorro que Paula, si entre ambos desean comprar un auto de $20.000, Luis debería tener el triple de dinero que tiene. ¿Cuánto dinero tiene Paula? ;3400;5000;4000;3500;2
Selecciona la respuesta correcta al planteamiento: Un auto avanza 13 kilómetros, luego retrocede 1100 metros, vuelve a avanzar 6 kilómetros, ¿cuántos metros avanzó realmente? ;1200;17900;19200;18200;2
Encuentra la respuesta correcta al planteamiento: Un estudiante falla en el 30% de las preguntas de una prueba. Si la prueba tiene un total de 200 preguntas, en promedio, ¿en cuántas preguntas se espera que acierten? ;140;160;190;165;1
Encuentra la respuesta correcta al planteamiento: Los 4/5 de un número es 60, ¿cuánto será los 2/3 del mismo número? ;60;50;20;32;2
Encuentre el porcentaje correcto: La molécula de un compuesto está hecho de elementos químicos. Si 60% es Oxígeno, 17% Carbono, 12% Hidrógeno y 7% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ;3%;4%;95%;96%;2
Encuentra la respuesta correcta al planteamiento: Pedro 36 caramelos, regala 12, le roban 9, pierde 5 y compra otras 8. Si divide en partes iguales a sus amigos, ¿cuántas caramelos recibirán cada uno de los  3 niños a los que debe entregar?;2;6;3;4;2
"Encuentra la respuesta correcta al planteamiento: En el colegio ""Rockero"", a 60 de sus 80 estudiantes les gusta la cumbia. En el colegio ""Salsero"" hay 100 estudiantes y a 80 les gusta la cumbia. En el colegio ""Cumbiero"" hay 160 estudiantes y a 40 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia? ";" ""Cumbiero"" y ""Rockero"" ";" ""Salsero""";" ""Cumbiero"" ";" ""Rockero""";2
Encuentra la respuesta correcta al planteamiento: El ingreso promedio mensual de tres hermanos es de $1700. El mayor tiene un sueldo de $900, el segundo gana $1500. ¿Cuál será el sueldo del hermano menor? ;3100;1900;2700;1350;3
Encuentra la respuesta correcta al planteamiento: Un cohete espacial, que puede viajar a 800 millas por hora, se mantiene en la base durante 6 horas desde las 05:00 am. Cuando despega, se desplaza a 850 millas por hora, ¿cuántas millas llevará recorridos a las 8:00 pm? ;6000;7200;7650;6750;3
Selecciona la respuesta correcta al planteamiento: Si Luis tiene 14 años y su madre tres veces la edad que él. Cuando Luis tenga 22 años, ¿cuántos tendrá su madre? ;48;92;50;58;3
Encuentra la respuesta correcta al planteamiento: El precio de un par de cafeteras es de $600 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 15%;380;580;400;345;4
Selecciona la respuesta correcta al planteamiento: Si una moto avanza a 180 km/h durante 45 minutos y luego a 60 km/h durante 20 minutos, ¿cuántos kilómetros recorre durante su trayecto? ;110;120;155;105;3
Encuentra la respuesta correcta al planteamiento: Un tren hace 8 viajes por mes. Cada mes, el operario revisa 8 veces los maquinas, 6 los frenos, 12 el combustible. En siete meses, ¿cuántas veces habrá revisado las maquinarias, los frenos y el combustible, respectivamente? ; 56, 40, 84; 56, 42, 84 ; 56, 42, 74; 56, 40, 84 ;2
Encuentra la respuesta correcta al planteamiento: Una familia compra 120 almuerzos. El 46% de ellos eran de carne, el 14% eran de pollo y los demás de vegetales, ¿cuántos eran de vegetales? ;56;48;23;32;2
Selecciona la respuesta correcta al planteamiento: La nota final de Juan en algebra es de 8,8 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 8,2 y en el segundo 8,4, ¿cuál fue su nota en el tercer examen? ;9.9;10;9.7;9.8;4
Encuentra la respuesta correcta al planteamiento: Un garaje de autos tiene 220 unidades, el 35% de ellos son autos y el 15% motos. ¿Cuántos hay de cada uno? ; 77 autos y 33 motos; 75 autos y 33 motos; 77 autos y 43 motos; 80 autos y 33 motos;1
Encuentre el porcentaje correcto: Diariamente, el 25% del Ecovía va ocupado por hombres menores de 65 y el 65% por mujeres menores de 65. Del restante, 40% son mujeres, ¿qué porcentaje del total representan? ;30%;8%;6%;4%;4
Encuentra la respuesta correcta al planteamiento: En una jornada de 6 horas se pintan 22 metros cuadrados de pared y se emplean 4 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 110 metros cuadrados? ; 20 horas y 7,5 litros de pintura; 30 horas y 20 litros de pintura ; 80 horas y 18 litros de pintura ; 40 horas y 6,5 litros de pintura ;2
Encuentre el porcentaje correcto: Si un arquitecto gasta 30,5% de su salario en vivienda, 22,5% en comida, 16% en salud y 9% en educación, ¿de cuánto puede disponer para sus demás gastos? ;16%;15%;22%;78%;3
Selecciona la respuesta correcta al planteamiento: Si un par de sillas cuesta $200, una mesa $160 y un florero $70, ¿cuánto debe pagarse por 3 camas, 4 mesas y 2 floreros? ;1030;1380;2700;2600;2
Encuentra la respuesta correcta al planteamiento: Luis tiene el doble de ahorro que Jorge, si entre ambos desean comprar un auto de $21.000, Luis debería tener el triple de dinero que tiene. ¿Cuánto dinero tiene Jorge? ;4000;2400;2000;3000;4
Encuentra la respuesta correcta al planteamiento: Un automóvil va a una velocidad de 60 km/h y se detiene 7 minutos cada hora. Si circula durante 10 horas, ¿cuántos kilómetros recorre en ese tiempo? ;340;376;530;400;3
"Selecciona la respuesta correcta al planteamiento: En una competencia corre 16000 metros, camina 7 km; nada 3000 metros más, conduce en bicicleta otros 5 km. ¿De cuántos kilómetros fue su recorrido?";35;31;33;32;2
Encuentra la respuesta correcta al planteamiento: El 35% de los parques en una ciudad son vigilados. Si en la ciudad hay 180 parques, ¿cuántos parques no vigilados hay en toda la ciudad? ;82;85;117;810;3
Encuentra la respuesta correcta al planteamiento: Se desea distribuir 272 esferos, 374 cuadernos, 238 libros y 153 lápices entre 17 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?; 16 esferos, 22 cuadernos, 10 libros y 9 lápices ; 19 esferos, 14 cuadernos, 14 libros y 9 lápices; 16 esferos, 14 cuadernos, 14 libros y 9 lápices ; 16 esferos, 22 cuadernos, 14 libros y 9 lápices ;4
Selecciona la respuesta correcta al planteamiento: En una plaza se utilizan 280 litros de agua, 120 litros se utilizan para limpiar los pisos, se lavan puestos y paredes con 60 litros, se lavan las gradas con el 5% y lo mismo se emplea en el jardines. ¿Cuántos litros se utilizan para los jardines? ";18;14;16;17;2
Encuentra la respuesta correcta al planteamiento: Una persona camina durante 50 minutos a 18 km/h, luego pausa 6 minutos y corre otros 25 minutos a 24 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ;20;25;29;27;2
Encuentra la respuesta correcta al planteamiento: Una persona tiene $390 en cinco cupones y cuatro de ellos son de $80 cada uno, ¿de cuánto es el otro cupón? ;$70;$215;$80;$90;1
Encuentra la respuesta correcta al planteamiento: Si un viaje individual a Esmeraldas cuesta $300, uno a Manta $450 y uno a Galápagos $700, ¿cuánto costaría a un par de parejas hacer los 3 viajes en un año? ;5560;6760;3660;5800;4
Selecciona la respuesta correcta al planteamiento: Un auto de carreras va a una velocidad de 170 km/h y uno urbano lo hace a 75 km/h. Después de 5 horas, ¿cuántos kilómetros habrá de diferencia entre ambos? ;375;475;630;540;2
Encuentre el porcentaje correcto: Para cenar, unos amigos piden 7 pizzas. Cada pizza tiene 10 rebanadas. Se comen el 73% en el restaurante, se llevan a casa el 11% y dejan lo demás. ¿Cuánto dejaron? ;88%;84%;16%;12%;3
Encuentra la respuesta correcta al planteamiento: Se vendió una radio con una ganancia del 25% sobre el precio de costo. Si se ha vendido en $115, hallar el precio de costo. ;79;80;92;78;3
Encuentra la respuesta correcta al planteamiento: El 40% de 6 horas es equivalente en minutos a:;144;108;109;432;1
Encuentra la respuesta correcta: Si 9 personas se comen 80 bocaditos en 25 minutos, ¿cuánto demorarán 15 personas en comer la misma cantidad? ;13;11;15;12;3
Selecciona la respuesta correcta al planteamiento: Varias familias van de paseo en 9 autos. Cuatro autos llevan familias de 5 personas cada uno. En dos autos viajan tres personas y tres van ocupados por solo dos personas.  ¿Cuántas personas viajan en total? ;37;36;35;32;4
Encuentra la respuesta correcta al planteamiento: Si el dólar se devaluará cada año 2%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024? ;96%;76%;68%;94%;4
Encuentra la respuesta correcta al planteamiento: Si manzana=$5, limón=$50, naranja=$125, ¿cuántas manzanas se pueden comprar por cada naranja? ;27;25;26;23;2
Encuentre el porcentaje correcto: Una estatua está compuesta de 5 elementos: 22% de arena, 15% de Hierro, 17% de yeso y 2% de madera, ¿cuál será el porcentaje de aluminio que posee? ;53%;44%;57%;43%;2
Selecciona la respuesta correcta al planteamiento: El ingreso mensual de un profesional es de $1500. Al ascender a Coordinador, su sueldo aumentará 45%. ¿Cuál será su nuevo ingreso mensual? ;2350;1520;1620;2175;4
Encuentra la respuesta correcta al planteamiento: El 70% de 30 semanas equivale a _____ días ;156;980;147;200;3
Encuentra la respuesta correcta al planteamiento: Al comprar un auto, cuyo precio es de $12000, nos hacen un descuento del 35%, ¿cuánto hay que pagar por el vehículo? ;6500;8020;7800;6400;3
`;
const dataRN = preguntasRazonamientoNumerico.split(/\r?\n|\r/);
export function preguntaRazonamientoNumerico(indice) {
  return dataRN[indice].split(";");
}